imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:

framework:
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    format_listener:
        enabled: true
        rules:
            - { path: '^/api/', fallback_format: json }

kwf:
    csrf_protection:
        ignore_paths:
            - /api/v1/oauth

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            origin_regex: true
            allow_credentials: true
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'OPTIONS', 'POST']
            max_age: 3600
