speaker-search:
    path: /api/v1/speakers/search
    methods: [GET]
    defaults:
        _controller: App\Controller\SpeakersController::searchAction

circle-groups:
    path: /api/v1/circle-groups
    methods: [GET]
    defaults:
        _controller: App\Controller\CircleGroupsController::getAction

congregations:
    path: /api/v1/congregations
    methods: [GET]
    defaults:
        _controller: App\Controller\CongregationsController::getAction

oauth-auth:
    path: /api/v1/oauth/authorize
    methods: [GET]
    defaults:
        _controller: App\OAuth\Controller\AuthorizeController::handleAuthorizeAction
oauth-token:
    path: /api/v1/oauth/token
    methods: [POST]
    defaults:
        _controller: App\OAuth\Controller\TokenController::tokenAction
oauth-well-known-openid-configuration:
    path: /api/v1/oauth/.well-known/openid-configuration
    methods: [GET]
    defaults:
        _controller: App\OAuth\Controller\WellKnownController::getConfigurationAction
openid-userinfo:
    path: /api/v1/oauth/oidc/userinfo
    methods: [GET]
    defaults:
        _controller: App\OAuth\Controller\OpenIdUserInfoController::userinfoAction
openid-jwks:
    path: /api/v1/oauth/oidc/jwks
    methods: [GET]
    defaults:
        _controller: App\OAuth\Controller\OpenIdJWKSController::getJWTSetsAction
