# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

services:
# Models
    app.model.speakers:
        class: Speakers
        factory: ['Kwf_Model_Abstract', getInstance]
        arguments: ['Speakers']

    app.handler.speakers:
        class: KwfBundle\Rest\Handler
        arguments:
            - "@app.model.speakers"
            - "@security.authorization_checker"
            - "@validator"
